### ISSUE TITLE
Working perfectly for EXTRA_SMALL_ACO only 

### ISSUE THREAD

**Issue by vikjin** [PearlHealth/bcda-quickstart#3]
Hi, 

First of all thanks, for the big help to see the sandbox data and I was successful in getting EXTRA_SMALL_ACO dataset. 

For other ACOs I updated the runner.py (two places, change ACO type), and each time I got 0% progress and  "Job taking longer than expected, check later" error. 

I feel I am doing something wrong for all the ACOs except  EXTRA_SMALL_ACO, 

can you help

**Comment by kharoutaj** [comment]
This [PR ](https://github.com/PearlHealth/bcda-quickstart/pull/4)should resolve these issues

**Comment by msolnit** [comment]
Closing this issue, since the PR was merged last year.
